server:
  port: 8081

spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:8081/lotto
      auto-index-creation: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

lotto:
  result-checker:
    lotteryRunOccurrence: "0 55 11 * * 6"
  number-generator:
    lotteryRunOccurrence: "0 0 12 * * 6"
    http:
      client:
        config:
          uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com
          port: 9090
          connectionTimeout: 5000
          readTimeout: 5000
  number-receiver:
    facade:
      count: 6
      lowBound: 1
      highBound: 99
